language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode7.2
      before_install:
        - brew install mariadb
        - mysql.server start
      latex: false
    - os: osx
      osx_image: xcode7.2
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
